kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-spring-boot-web
  labels:
    app: sample-spring-boot-web
    app.kubernetes.io/component: sample-spring-boot-web
    app.kubernetes.io/instance: sample-spring-boot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sample-spring-boot-web
  template:
    metadata:
      labels:
        deployment: sample-spring-boot-web
    spec:
      containers:
        - name: sample-spring-boot-web
          image: 'image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/sample-spring-boot-web:${IMAGE_TAG}'
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8443
              protocol: TCP
              name: https
---
apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-web
spec:
  type: ClusterIP
  selector:
    app: sample-spring-boot-web
  ports:
    - port: 8080
      name: http
    - port: 8443
      name: https